export const ADD_ALL_POKEMONS = "ADD_ALL_POKEMONS";
export const SEARCH_POKEMON = "SEARCH_POKEMON";
export const DETAIL_POKEMON = "DETAIL_POKEMON";
export const TYPES_POKEMONS = "TYPES_POKEMONS";
export const SET_FILTERS = "SET_FILTERS";
